### PR TITLE
#32: vt-tv: Improve CI

### LINKED ISSUE #32: vt-tv: Improve CI
Replicate functionality and workflow of Magistrate CI.

- [ ] Add more tests
- [ ] Test API
- [ ] Test exported meshes
- [ ] Test the problematic configuration for #70 with a macOS runner

### LINKED ISSUE #69: Clarify and document build process
- Unify variables used during all builds (bindings and C++ standalone) => allow `setup.py` to use all optional variables that can be used in `CMakeLists.txt`
- Document these variables
- Provide an example script to build the standalone C++ executable

### LINKED ISSUE #92: Investigate Build error with clang-14
When using clang-14 / clang-14++ as compiler we get some build error if we activate warnings as errors (
-DCMAKE_CXX_FLAGS="-Werror" or -DVT_TV_WERROR_ENABLED=ON)
This might be linked to yaml-cpp

Here is the output I got
```
[ 83%] Building CXX object src/CMakeFiles/vt-tv.dir/vt-tv/utility/json_reader.cc.o
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.cc:44:
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.h:49:
In file included from /home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/yaml.h:12:
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/emitterstyle.h:12:25: error: declaration shadows a variable in namespace 'YAML' [-Werror,-Wshadow]
  enum value { Default, Block, Flow };
                        ^
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/emittermanip.h:59:3: note: previous declaration is here
  Block,
  ^
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.cc:44:
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.h:49:
In file included from /home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/yaml.h:12:
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/emitterstyle.h:12:32: error: declaration shadows a variable in namespace 'YAML' [-Werror,-Wshadow]
  enum value { Default, Block, Flow };
                               ^
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/emittermanip.h:58:3: note: previous declaration is here
  Flow,
  ^
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.cc:44:
In file included from /home/thomas/repositories/vt-tv/src/vt-tv/utility/parse_render.h:49:
In file included from /home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/yaml.h:16:
In file included from /home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/node/node.h:18:
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/node/type.h:12:27: error: declaration shadows a variable in namespace 'YAML' [-Werror,-Wshadow]
  enum value { Undefined, Null, Scalar, Sequence, Map };
                          ^
/home/thomas/repositories/vt-tv/lib/yaml-cpp/include/yaml-cpp/null.h:23:27: note: previous declaration is here
extern YAML_CPP_API _Null Null;
                          ^
/home/thomas/repositories/vt-tv/src/vt-tv/render/render.cc:66:34: error: comparison of integers of different signs: 'int' and 'uint64_t' (aka 'unsigned long') [-Werror,-Wsign-compare]
  if(sqrt_n_ranks * sqrt_n_ranks == n_ranks_) {
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~
1 error generated.
gmake[2]: *** [src/CMakeFiles/vt-tv.dir/build.make:76: src/CMakeFiles/vt-tv.dir/vt-tv/render/render.cc.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
3 errors generated.
gmake[2]: *** [src/CMakeFiles/vt-tv.dir/build.make:146: src/CMakeFiles/vt-tv.dir/vt-tv/utility/parse_render.cc.o] Error 1
```

### LINKED ISSUE #103: Remove unimplemented object communicator methods
Remove `summarizeUnidirectional` and `summarize` methods from `ObjectCommunicator` as brought up [here](https://github.com/DARMA-tasking/vt-tv/pull/85/files#r1695043132).

### PR DESCRIPTION
**Pull request by tlamonthezie**
Fixes #32 
Fixes #92
Fixes #103 
Might fix #69 

**Important! Dockerhub repository is modified from that PR (now same that `vt` one). Base docker images are used for unit tests and are not already pushed to the new repository which will generate failures on CI until merge is done.**

**One of the latest run (using old repository) can be found at https://github.com/DARMA-tasking/vt-tv/actions/runs/10177046856**

**After merging please call the `pushdockerimage` action to push base images (with VTK) to the new Dockerhub repository. Until that CI will fail**

This PR includes:

Unit tests refactoring and writing:
1. Remove obsolete code in the `tests` & `example` directories
2. Move GoogleTest and its & fetch script to `lib` directory + update the fetch script.
3. Re-organize the tests directory and update CMakeLists under `tests/unit` and build tests in a single executable for Google test optimal use.
4. Add unit tests mainly for the api classes
5. Add TESTING.md documentation to get started with testing.
6. Add root `build.sh` script capable for local use as well as for ci use with some options for build, coverage and test run. get more info with `build.sh --help`. This provides for example a way to generate coverage html report, JUnit report etc.
7. Add simple diff test for CCM example PNG output with some tolerance. See `tests/test_image.sh` (Call internally a python module for now to diff between actual and expected png image).  (This is called by the ParseRenderTest class after rendering with the `ccm_example0.png` generated file).
8. Remove ctest calls to use only GTest directly (Test compiled in a file)
9. Reorganize tests data files and config files and re-generate `lb_synthetic_data` using the `create_synthetic_attributes_data.py` script (and reorganize generated attributes alphabetically in the python script)

CI:
1. Add `xvfb` as graphics display in CI.
2. Make python bindings test working in CI and include in the Build & Test pipeline workflow (remove test bindings workflow). See `ci/docker/build-and-test.dockerfile` and called shell script for details.
3. Include Test results & Coverage in Github step summary of job run.
4. Upgrade external used github actions (some versions were deprecated)
5. Make docker image configurable (base image, compiler, VTK version, Python version). 
5.1 Configurable base image: `ci/docker/make-base.dockerfile` used by the `.github/workflows/pushbasedockerimage.yml` . The `pushbasedockerimage` contains now an input to select the image to build and push to DockerHub.
5.2 Configurable vt-tv build & test image `ci/docker/build-and-test.dockerfile` used by the `.github/workflows/build-and-test.yml` workflow
5.3 Provide test matrix using the 3 images in the build & test workflow: 
    - `ubuntu_22.04-gcc_11-vtk_9.2.2-py_3.8` (Build, Test)
    - `ubuntu_22.04-clang_14-vtk_9.2.2-py_3.8` (Build, Test)
    - `ubuntu_22.04-gcc_12-vtk_9.3.0-py_3.8` (Build, Test, Coverage)
 6. Add CMake options (enable tests, enable coverage)

Because docker images are more scalable it will be easier to add later additional configurations to the `pushbasedockerimage.yml` workflow and to add it to tests in the `build-and-test.yml` images to build vt-tv on and to run tests on.
Additionnaly the `ci ` folder` has been re-organized and docker images are now in the new `ci/docker` directory

Additionally added fix from #92 to make checks successful for clang.

### CODE REVIEW

File: tests/unit/api/test_object_communicator.cc [hunk 1]
```diff
@@ -0,0 +1,219 @@
...
+/**
+ * Test ObjectCommunicator initial state
+ */
+TEST_F(ObjectCommunicatorTest, test_summarize_communications_count) {
+  GTEST_SKIP() << "ObjectCommunicator::summarize seems in WIP and is never called";
+
+  // std::make_pair(w_sent, w_recv);
+  auto summary = comm_0.summarize();
+  EXPECT_EQ(summary.first.size(), 3);
+  EXPECT_EQ(summary.second.size(), 2);
```
Comment (cwschilly) [inline tests/unit/api/test_object_communicator.cc:144]: Since this test isn't being run, I think we can just delete this stuff

File: tests/unit/api/test_object_work.cc [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+
+#include <vt-tv/api/object_work.h>
+
+#include <fmt-vt/format.h>
+
+#include <string>
+#include <filesystem>
+#include <iostream>
+#include <variant>
+#include <set>
```
Comment (cwschilly) [inline tests/unit/api/test_object_work.cc:54]: We could move all testing includes inside a separate `test_helpers.h` file to reduce duplication across tests

File: tests/unit/generator.h [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+                #endif
+                {
+                info.addInfo(tmpInfo->getObjectInfo(), tmpInfo->getRank(rank));
+                }
+            }
+            return info;
+        }
+};
+
+}
```
Comment (cwschilly) [inline tests/unit/generator.h:200]: missing newline

File: tests/unit/render/test_parse_render.cc [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+/**
+ * Provides unit tests for the vt::tv::utility::ParseRender class to test with config file input
+ */
+class ParseRenderTest :public ::testing::TestWithParam<std::string> {
+
+  void SetUp() override {
+    // Disable this test because of gcc segfault at vtkWindowToImageFilter (memcpy) if save png is true in config
+    // GTEST_SKIP();
+    // return;
+
```
Comment (cwschilly) [inline tests/unit/render/test_parse_render.cc:72]: Can we remove these comments now?

File: tests/unit/render/test_render.cc [hunk 5]
```diff
@@ -0,0 +1,199 @@
...
+/**
+ * Provides unit tests for the vt::tv::render::Render class to test with config file input
+ */
+class RenderTest :public ::testing::TestWithParam<std::string> {
+
+  void SetUp() override {
+    // Disable this test because of gcc segfault at vtkWindowToImageFilter (memcpy) if save png is true in config
+    // GTEST_SKIP();
+    // return;
+
```
Comment (cwschilly) [inline tests/unit/render/test_render.cc:74]: Can we delete these comments?

File: tests/unit/render/test_render.cc [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+          config["viz"]["x_ranks"].as<uint64_t>(),
+          config["viz"]["y_ranks"].as<uint64_t>(),
+          config["viz"]["z_ranks"].as<uint64_t>()
+        },
+        config["viz"]["object_jitter"].as<double>(),
+        output_dir,
+        config["output"]["file_stem"].as<std::string>(),
+        1.0,
+        config["viz"]["save_meshes"].as<bool>(),
+        // config["viz"]["save_pngs"]: Let PNG rendering to the ParseRenderTest test class.
```
Comment (cwschilly) [inline tests/unit/render/test_render.cc:115]: Can we delete this comment?

File: tests/unit/render/test_render.cc [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+  YAML::Node config = YAML::LoadFile(fmt::format("{}/tests/config/{}", SRC_DIR, config_file));
+  Info info = Generator::loadInfoFromConfig(config);
+
+  uint64_t win_size = 2000;
+  uint64_t font_size = 50;
+
+  std::string output_dir;
+  if (config["viz"]["object_qoi"].as<std::string>() == "shared_block_id") {
+    // Temporary: this case must be removed as soon as the `shared_block_id` QOI becomes supported.
+    EXPECT_THROW(createRender(config, info, output_dir), std::runtime_error); // "Invalid Object QOI: shared_block_id"
```
Comment (cwschilly) [inline tests/unit/render/test_render.cc:136]: `shared_block_id` should be supported via the `attributes` feature of vttv (see[ this comment](https://github.com/DARMA-tasking/vt-tv/issues/80#issuecomment-2233686338))

File: tests/unit/render/test_render.cc [hunk 8]
```diff
@@ -0,0 +1,199 @@
...
+
+    // Check: that number of generated mesh files (*.vtp) correspond to the number of phases
+    std::string output_file_stem = config["output"]["file_stem"].as<std::string>();
+    for (uint64_t i = 0; i<info.getNumPhases(); i++) {
+      ASSERT_TRUE(std::filesystem::exists(fmt::format("{}{}_rank_mesh_{}.vtp", output_dir, output_file_stem, i))) << fmt::format("{}{}_rank_mesh_{}.vtp", output_dir, output_file_stem, i);
+      ASSERT_TRUE(std::filesystem::exists(fmt::format("{}{}_object_mesh_{}.vtp", output_dir, output_file_stem, i))) << fmt::format("{}{}_rank_mesh_{}.vtp", output_dir, output_file_stem, i);
+    }
+
+    // Validate mesh files (*.vtp) content ?
+    // Is it needed
```
Comment (cwschilly) [inline tests/unit/render/test_render.cc:150]: I think it is necessary--we want to make sure all output files are correct. @pierrepebay What do you think?

File: tests/unit/util.h [hunk 9]
```diff
@@ -41,40 +41,49 @@
...
+            return std::make_tuple(status, output);
+    }
+};
 
-  // Instantiate render
-  auto r = Render(*info);
-  r.generate();
-  return 0;
-}
+}
```
Comment (cwschilly) [inline tests/unit/util.h:89]: missing newline

**Review by cwschilly — COMMENTED** [review]
Mostly minor changes--everything looks great on the whole. I do think we should test the content of the mesh files though.

File: .github/workflows/find-trailing-whitespace.yml [hunk 10]
```diff
@@ -7,7 +7,7 @@ jobs:
     name: Find Trailing Whitespace
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
       - uses: DARMA-tasking/find-trailing-whitespace@master
         with:
-          exclude: "sketches;lib;docs"
+          exclude: "sketches;lib;docs;ccm_example0.png"
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/find-trailing-whitespace.yml]: Fixed using `.png$` as the command run by the action to filter is `ls | grep -v ".png$"` to exclude a file

File: tests/unit/render/test_render.cc (hunk 5 above)
Comment (tlamonthezie) [reply tests/unit/render/test_render.cc:74]: Done

File: tests/unit/render/test_render.cc (hunk 6 above)
Comment (tlamonthezie) [reply tests/unit/render/test_render.cc:115]: Done

File: .github/workflows/build-and-test.yml [hunk 11]
```diff
@@ -0,0 +1,94 @@
...
+
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        image:
+        - ubuntu_22.04-gcc_11-vtk_9.2.2-py_3.8
+        - ubuntu_22.04-clang_14-vtk_9.2.2-py_3.8
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/build-and-test.yml:19]: New image has been pushed and added to the tests: `ubuntu_22.04-gcc_12-vtk_9.3.0-py_3.8`

File: .vscode/c_cpp_properties.json [hunk 12]
```diff
@@ -0,0 +1,21 @@
...
+            "includePath": ["${env:includePath}"],
+            "defines": ["${env:defines}"],
+            "compilerPath": "/usr/bin/clang",
+            "cStandard": "c17",
+            "cppStandard": "c++17",
+            "intelliSenseMode": "linux-clang-x64"
+        }
+    ],
+    "version": 4
+}
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .vscode/c_cpp_properties.json]: Fixed

File: .vscode/settings.json [hunk 13]
```diff
@@ -0,0 +1,86 @@
...
+        "streambuf": "cpp",
+        "thread": "cpp",
+        "cfenv": "cpp",
+        "typeindex": "cpp",
+        "typeinfo": "cpp",
+        "valarray": "cpp",
+        "variant": "cpp",
+        "*.ipp": "cpp"
+    }
+}
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .vscode/settings.json]: Fixed

File: TESTING.md [hunk 14]
```diff
@@ -0,0 +1,13 @@
+## Unit Testing
+
+### Running unit tests
+
+Unit tests are implemented using thhe [Google's C++ test framework](https://github.com/google/googletest).
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply TESTING.md]: Fixed

File: TESTING.md [hunk 15]
```diff
@@ -0,0 +1,13 @@
...
+The tests source files are located under the `tests` directory as test_*.cpp.
+
+To build and test vt-tv use the `build.sh` script
+Type `build.sh --help` to get started.
+
+You might want also directly run the tests from the build:
+`{VT_TV_BUID_DIR}/tests/unit/AllTests`
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply TESTING.md]: Fixed

File: ci/build.sh [hunk 16]
```diff
@@ -1,12 +1,16 @@
...
+# (Specific path, enable tests and coverage, warnings as errors)
+bash -c "VT_TV_BUILD_DIR=/opt/build/vt-tv \
+    VTK_DIR=/opt/build/vtk \
+    VT_TV_TESTS_ENABLED=ON \
+    VT_TV_COVERAGE_ENABLED=${VT_TV_COVERAGE_ENABLED:-OFF} \
+    VT_TV_WERROR_ENABLED=ON \
+    /opt/src/vt-tv/build.sh"
 
-time cmake --build /opt/build/vt-tv --parallel $(nproc)
+echo "VT-TV build success"
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply ci/build.sh]: Fixed

File: config/conf.yaml [hunk 17]
```diff
@@ -16,4 +16,4 @@ viz:
 output:
   directory: output
   file_stem: lb_test
-  window_size: 2000
+  window_size: 2000
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply config/conf.yaml]: Fixed

File: lib/fetch_googletest.sh [hunk 18]
```diff
@@ -1,18 +1,22 @@
...
-pushd googletest
+pushd $GTEST_DIR
 rm -fr .[!.]* BUILD.bazel WORKSPACE appveyor.yml library.json platformio.ini
 rm -fr ci/
-rm -fr googlemock/
 rm -fr googletest/test/ googletest/samples/ googletest/docs/ googletest/scripts/
+rm -fr googlemock/test/ googlemock/samples/ googlemock/docs/ googlemock/scripts/
 rm -fr docs
-popd
+popd
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply lib/fetch_googletest.sh]: Fixed

File: lib/fetch_googletest.sh [hunk 19]
```diff
@@ -1,18 +1,22 @@
 #! /bin/sh
 
-GTEST_BRANCHTAG=release-1.12.1
+GTEST_BRANCHTAG=release-1.12.1 # next is v1.14.0
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply lib/fetch_googletest.sh:3]: @cwschilly changing a dependency version should be requested in another issue. There were a discussion with @lifflander about that some weeks ago because I had envisaged to replace fetch script by a fetch action from CMakeLists.

File: setup.py [hunk 20]
```diff
@@ -32,11 +32,11 @@ def build_extension(self, ext):
...
-    vtk_dir = os.environ.get('VTTV_VTK_DIR')
+    vtk_dir = os.environ.get('VTK_DIR')
     if not vtk_dir:
-      raise RuntimeError("Environment variable VTTV_VTK_DIR is required")
+      raise RuntimeError("Environment variable VTK_DIR is required")
 
-    jobs = os.environ.get('VTTV_CMAKE_JOBS', os.cpu_count())
+    jobs = os.environ.get('VT_TV_CMAKE_JOBS', os.cpu_count())
 
     n_threads = os.environ.get('VTTV_N_THREADS', 1)
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply setup.py]: Fixed

File: tests/unit/generator.h (hunk 3 above)
Comment (tlamonthezie) [reply tests/unit/generator.h]: Fixed

File: tests/unit/api/test_object_work.cc (hunk 2 above)
Comment (tlamonthezie) [reply tests/unit/api/test_object_work.cc]: Done.

File: tests/unit/render/test_parse_render.cc (hunk 4 above)
Comment (tlamonthezie) [reply tests/unit/render/test_parse_render.cc]: Done

File: tests/unit/render/test_render.cc (hunk 7 above)
Comment (tlamonthezie) [reply tests/unit/render/test_render.cc]: attribute value is restored. Faling in CI for the moment

File: tests/unit/util.h (hunk 9 above)
Comment (tlamonthezie) [reply tests/unit/util.h]: Fixed

File: lib/fetch_googletest.sh (hunk 19 above)
[the remark this answers is not in the document]
Comment (cwschilly) [reply lib/fetch_googletest.sh:3]: Sounds good!

**Review by ppebay — COMMENTED** [review]
Please create follow-on issues @tlamonthezie for aspects that are not covered yet by CI but that we discussed at last meeting.

File: tests/config/ccm-example.yaml [hunk 21]
```diff
@@ -0,0 +1,18 @@
...
+  directory: tests/data/ccm_example
+  n_ranks: 2
+
+viz:
+  x_ranks: 2
+  y_ranks: 1
+  z_ranks: 1
+  object_jitter: 0.5
+  rank_qoi: load
+  object_qoi: load # shared_block_id
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply tests/config/ccm-example.yaml]: Done

File: tests/test_image.sh [hunk 22]
```diff
@@ -0,0 +1,25 @@
...
+
+pip install imgcompare --quiet 2>/dev/null
+
+DIFF=$(printf "%.2f" $(python -c 'import imgcompare; print(imgcompare.image_diff_percent("'$ACTUAL'", "'$EXPECTED'"));'))
+if { echo $TOLERANCE ; echo $DIFF ; } | sort -n -c 2>/dev/null; then
+    echo "Image diff = $DIFF%. Tolerance is $TOLERANCE"
+    exit 2
+fi
+
+exit 0
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply tests/test_image.sh:25]: Fixed

File: tests/unit/api/test_info.cc [hunk 23]
```diff
@@ -0,0 +1,455 @@
...
+  }
+
+  friend std::ostream& operator<< (std::ostream& stream, const InfoTestParam& param) {
+    stream << "{num_objects: " << std::to_string(param.num_objects) << ", num_ranks: " << std::to_string(param.num_ranks) << ", num_phases: " << std::to_string(param.num_phases) << "}";
+    return stream;
+  }
+
+  const size_t num_objects;
+  const int16_t num_ranks;
+  const uint64_t num_phases;
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply tests/unit/api/test_info.cc]: If it is used only there in a single test file I think it is not needed. @pierrepebay what do you think ?

File: tests/unit/api/test_object_communicator.cc (hunk 1 above)
Comment (tlamonthezie) [reply tests/unit/api/test_object_communicator.cc:137]: In fact there is an underlying question ! It seems that the `summarize` method is never called from the source. Furthermore this method implementation (class `ObjectCommunicator`) always returns a pair of empty vectors due to commented code in `summarizeUnidirectional` method. Is there any reason to keep this in sources ? Until we determine that point I suggest to let this skipped test. If it must be kept I think @pierrepebay you can create a follow up issue

File: tests/unit/render/test_render.cc (hunk 8 above)
Comment (tlamonthezie) [reply tests/unit/render/test_render.cc]: Added to the follow up issue #95 because we have to know in terms of file content which specification we want to apply for these tests. A raw diff cannot be done because files are never the same. But some XML nodes presence or attributes might be tested.

**Comment by tlamonthezie** [comment]
> Please create follow-on issues @tlamonthezie for aspects that are not covered yet by CI but that we discussed at last meeting.

The issue 

> Please create follow-on issues @tlamonthezie for aspects that are not covered yet by CI but that we discussed at last meeting.



> Please create follow-on issues @tlamonthezie for aspects that are not covered yet by CI but that we discussed at last meeting.

Hi @ppebay I created an issue to continue to wrok on the CI at #95 . Some additional things have also been added.

File: .github/workflows/build-and-test.yml [hunk 24]
```diff
@@ -0,0 +1,94 @@
...
+        id: docker_build
+        continue-on-error: false
+        uses: docker/build-push-action@v6
+        with:
+          push: false
+          tags: ${{ env.DOCKER_TAG }}
+          context: .
+          file: ./ci/docker/build-and-test.dockerfile
+          build-args: |
+            BASE_IMAGE=pierrpebay/vt-tv:${{ matrix.image }}
```
[the remark this answers is not in the document]
Comment (pierrepebay) [reply .github/workflows/build-and-test.yml:58]: They should be pushed to the repository vt pushes to.

[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/build-and-test.yml]: Done. Will require to call push action to generate base image on new Dockerhub repo after merging.

File: src/vt-tv/render/render.cc [hunk 25]
```diff
@@ -63,7 +63,7 @@ Render::Render(Info in_info)
   grid_size_[2] = 1; // we assume 2D representation
 
   int sqrt_n_ranks = std::sqrt(n_ranks_);
-  if(sqrt_n_ranks * sqrt_n_ranks == n_ranks_) {
+  if(static_cast<uint64_t>(sqrt_n_ranks) == n_ranks_) {
```
Comment (pierrepebay) [inline src/vt-tv/render/render.cc:66]: I think both the older way and the way you suggest doing are error prone; 
Here is what I believe to be the most robust approach:
```c++
uint64_t sqrt_n_ranks = static_cast<uint64_t>(std::sqrt(static_cast<double>(n_ranks_)));
if (sqrt_n_ranks * sqrt_n_ranks == n_ranks_) { // n_ranks_ is perfect square }
```

File: tests/data/ccm_example/data.0.json [hunk 26]
```diff
@@ -0,0 +1 @@
+{"metadata":{"type":"LBDatafile","rank":0},"phases":[{"id":0,"tasks":[{"entity":{"home":0,"id":0,"migratable":true,"type":"object"},"node":0,"resource":"cpu","time":2.0,"user_defined":{"shared_id":0,"shared_bytes":10000.0,"home_rank":0}},{"entity":{"home":0,"id":1,"migratable":true,"type":"object"},"node":0,"resource":"cpu","time":3.5,"user_defined":{"shared_id":0,"shared_bytes":10000.0,"home_rank":0}}],"communications":[{"type":"SendRecv","to":{"type":"object","id":2},"messages":1,"from":{"type":"object","id":0},"bytes":10000.0},{"type":"SendRecv","to":{"type":"object","id":2},"messages":1,"from":{"type":"object","id":1},"bytes":15000.0},{"type":"SendRecv","to":{"type":"object","id":1},"messages":1,"from":{"type":"object","id":0},"bytes":25000.0}]}]}
```
Comment (pierrepebay) [inline tests/data/ccm_example/data.0.json:1]: missing EOF newline

File: tests/data/ccm_example/data.1.json [hunk 27]
```diff
@@ -0,0 +1,44 @@
...
+                    "from": {
+                        "type": "object",
+                        "id": 2
+                    },
+                    "bytes": 20000.0
+                }
+            ]
+        }
+    ]
+}
```
Comment (pierrepebay) [inline tests/data/ccm_example/data.1.json:44]: missing EOF newline (same for other json files, not adding more comments)

**Review by pierrepebay — CHANGES_REQUESTED** [review]

File: .github/workflows/build-and-test.yml [hunk 28]
```diff
@@ -0,0 +1,95 @@
...
+
+      # - name: CCM Example output to summary (does not work: print plain text)
+      #   if: ${{ (success() || failure()) &&  env.VT_TV_TESTS_ENABLED == 'ON' }}
+      #   run: |
+      #     echo '## CCM Example output' >> $GITHUB_STEP_SUMMARY
+      #     if [ -f "${{ env.OUTPUT_DIR }}/tmp/artifacts/ccm_example0.png" ]; then
+      #       echo '!'"[CCM Example](${{ env.OUTPUT_DIR }}/tmp/artifacts/ccm_example0.png)" >> $GITHUB_STEP_SUMMARY
+      #     else
+      #       echo 'Missing !' >> $GITHUB_STEP_SUMMARY
+      #     fi
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/build-and-test.yml:87]: The work from #94 is another PR so if we plan to merge #94 first we have to do some checks for #85 after that

File: .github/workflows/pushbasedockerimage.yml [hunk 29]
```diff
@@ -1,32 +1,87 @@
-name: Build dependencies and push base Docker Image to dockerhub
+name: Build & push base Docker image
 
-on: workflow_dispatch
+on:
+  # # Push event: Useful for testing new image build on CI
+  # push:
+  #   branches:
+  #   - 32-vt-tv-improve-ci
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/pushbasedockerimage.yml:7]: Done

File: .github/workflows/pushbasedockerimage.yml [hunk 30]
```diff
@@ -1,32 +1,87 @@
...
     runs-on: ubuntu-latest
+    # Please comment the matrix when using the dispatch event and use inputs instead.
+    # Matrix for build tests on push event.
+    # strategy:
+    #   matrix:
+    #     image:
+    #     - ubuntu_22.04-gcc_11-vtk_9.2.2-py_3.8
+    #     - ubuntu_22.04-clang_14-vtk_9.2.2-py_3.8
+    #     - ubuntu_22.04-gcc_12-vtk_9.3.0-py_3.8
+    #     # - ubuntu_24.04-gcc_11-vtk_9.3.1-py_3.12 # FAILS
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/pushbasedockerimage.yml]: Done

File: src/vt-tv/render/render.cc (hunk 25 above)
Comment (tlamonthezie) [reply src/vt-tv/render/render.cc]: Oh yes I have introduced some error here while fixing a clang error...
Your solution is working. It has been applied.

File: tests/data/ccm_example/data.0.json (hunk 26 above)
Comment (tlamonthezie) [reply tests/data/ccm_example/data.0.json]: Fixed

File: tests/data/ccm_example/data.1.json (hunk 27 above)
Comment (tlamonthezie) [reply tests/data/ccm_example/data.1.json]: Fixed. (also restores unformatted json. it was formatted only for dev purpose)

File: .github/workflows/pushbasedockerimage.yml [hunk 31]
```diff
@@ -1,32 +1,87 @@
...
+  workflow_dispatch:
+    inputs:
+      image:
+        type: choice
+        description: The configuration to build as a combination of os, compiler, vtk and python versions
+        options:
+        - ubuntu_22.04-gcc_11-vtk_9.2.2-py_3.8
+        - ubuntu_22.04-clang_11-vtk_9.2.2-py_3.8
+        - ubuntu_22.04-gcc_12-vtk_9.3.0-py_3.8
+        # - ubuntu_24.04-gcc_14-vtk_9.3.0-py_3.12 # FAILS
```
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .github/workflows/pushbasedockerimage.yml]: Just removed the commented line for now as it is not latest vt configuration. Can be part of another issue in a future

File: .vscode/c_cpp_properties.json
[the remark this answers is not in the document]
Comment (tlamonthezie) [reply .vscode/c_cpp_properties.json:1]: @pierrepebay just a comment on that. If we decide to not include settings from IDE's it might be good to add a .gitignore entry. If no guideline is currently defined (I don't konw)I think there are pros and cons to keep or to remove that kind of files and then it can be the subject of a discussion.

[the remark this answers is not in the document]
Comment (nlslatt) [reply .vscode/c_cpp_properties.json:1]: @lifflander has the final say, but since I see system-specific paths in this file, it's probably not a good idea to commit. Adding it to .gitignore should be fine.

**Comment by nlslatt** [comment]
This is a huge PR. You might consider breaking it up into multiple PRs if it gets difficult to get everything passing.

File: .vscode/c_cpp_properties.json
[the remark this answers is not in the document]
Comment (cwschilly) [reply .vscode/c_cpp_properties.json:1]: I've removed the vscode settings from this PR and added `.vscode` to gitignore

File: tests/unit/api/test_object_communicator.cc (hunk 1 above)
Comment (pierrepebay) [reply tests/unit/api/test_object_communicator.cc:137]: `summarizeUnidirectional` and `summarize` are something I started adding because it was in `LBAF`, but never completely implemented. As you said it's not used anywhere, and I don't think it will as it isn't particularly useful for `vt-tv`. I think we can remove both functions, and those tests accordingly.

Comment (cwschilly) [reply tests/unit/api/test_object_communicator.cc]: I've removed these functions and their tests from vt-tv

File: tests/unit/api/test_object_info.cc [hunk 32]
```diff
@@ -2,7 +2,7 @@
 //@HEADER
 // *****************************************************************************
 //
-//                                test_harness.h
+//                           test_json_reader.cc
```
Comment (nlslatt) [inline tests/unit/api/test_object_info.cc:5]: Incorrect filename in header.

File: tests/unit/api/test_object_work.cc [hunk 33]
```diff
@@ -0,0 +1,109 @@
+/*
+//@HEADER
+// *****************************************************************************
+//
+//                           test_json_reader.cc
```
Comment (nlslatt) [inline tests/unit/api/test_object_work.cc:5]: Incorrect filename in header

**Review by nlslatt — COMMENTED** [review]
I noticed that style varies from file to file and I wonder if we should implement vt's style guidelines here as well, perhaps as a separate PR so we can get this merged sooner rather than later.

vt has a tool that will check/correct the header comments at the tops of files, including setting the correct filenames. There are more files that need to be corrected than I marked.

File: tests/unit/util.h [hunk 34]
```diff
@@ -0,0 +1,130 @@
+/*
+//@HEADER
+// *****************************************************************************
+//
+//                           test_json_reader.cc
```
[the remark this answers is not in the document]
Comment (cwschilly) [reply tests/unit/util.h]: Fixed

File: tests/unit/generator.h [hunk 35]
```diff
@@ -0,0 +1,191 @@
+/*
+//@HEADER
+// *****************************************************************************
+//
+//                           test_json_reader.cc
```
[the remark this answers is not in the document]
Comment (cwschilly) [reply tests/unit/generator.h]: Fixed

File: tests/unit/api/test_object_work.cc (hunk 33 above)
Comment (cwschilly) [reply tests/unit/api/test_object_work.cc]: Fixed

File: tests/unit/util.h (hunk 34 above)
[the remark this answers is not in the document]
Comment (cwschilly) [reply tests/unit/util.h]: Fixed

File: tests/unit/generator.h (hunk 35 above)
[the remark this answers is not in the document]
Comment (cwschilly) [reply tests/unit/generator.h]: Fixed

File: tests/unit/api/test_object_info.cc (hunk 32 above)
Comment (cwschilly) [reply tests/unit/api/test_object_info.cc]: Fixed

File: src/vt-tv/api/info.h [hunk 36]
```diff
@@ -2,10 +2,10 @@
 //@HEADER
 // *****************************************************************************
 //
-//                                  info.h
+//                                    info.h
 //             DARMA/vt-tv => Virtual Transport -- Task Visualizer
 //
-// Copyright 2019 National Technology & Engineering Solutions of Sandia, LLC
+// Copyright 2019-2024 National Technology & Engineering Solutions of Sandia, LLC
```
Comment (cwschilly) [inline src/vt-tv/api/info.h:8]: @nlslatt  The `license-template` in vt has the copyright from `2019-2021`--I changed this to 2019-2024. Is this correct, or should I stay with 2019-2021?

Comment (nlslatt) [reply src/vt-tv/api/info.h:8]: Sounds reasonable, but I don't know what the official answer is

Comment (cwschilly) [reply src/vt-tv/api/info.h:8]: We discussed this in the meeting and decided to use `2019-2024`

**Review by pierrepebay — APPROVED** [review]
